spring:
  profiles:
    include:
      - mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB