spring:
  profiles:
    include:
      - mysql
      - cloud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true

eagle:
  int:
    page : 10
    before_day : 30
    recent_day : 100
