version: '2'

services:
  redis-master:
    image: redis:alpine
    container_name: redis-master
    command: redis-server  --requirepass ${REDIS_PASSWORD} --appendonly no
    volumes:
      - /home/ubuntu/redis_data/master:/data
    ports:
      - "6379:6379"
    networks:
      - wm-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-slave:
    image: redis:alpine
    container_name: redis-slave
    command: redis-server --slaveof redis-master 6379 --requirepass ${REDIS_PASSWORD} --appendonly no
    volumes:
      - /home/ubuntu/redis_data/slave:/data
    ports:
      - "6380:6379"
    networks:
      - wm-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=slave
    restart: always

networks:
  wm-net:
    driver: bridge