spring:
  profiles:
    active: dev
    include:
      - core
      - mysql
      - oauth

#  devtools:
#    restart:
#      log-condition-evaluation-delta=false:
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
---
spring:
  config:
    activate:
      on-profile: dev
kafka:
  broker:
    address:
        "localhost:29092"

