spring:
  profiles:
    include:
      - core
      - mysql
      - oauth
  batch:
    jdbc:
      initialize-schema: embedded

logging:
  level:
    org:
      springframework:
        jdbc:
          core: INFO
        boot:
          autoconfigure: INFO