name: Server Batch CD

on:
  pull_request:
    branches: [ "main", "dev", "deploy-test"]
    paths:
      - 'core/**'
      - 'batch/**'
    types:
      - closed
jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/checkout@v3
      - name: 환경변수 입력
        run: |
          touch ./core/src/main/resources/application-mysql.yml
          echo "${{ secrets.APPLICATION_MYSQL }}" | base64 --decode > ./core/src/main/resources/application-mysql.yml
          touch ./core/src/main/resources/application-oauth.yml
          echo "${{ secrets.APPLICATION_OAUTH }}" | base64 --decode > ./core/src/main/resources/application-oauth.yml
          touch ./core/src/main/resources/application-redis.yml
          echo "${{ secrets.APPLICATION_REDIS }}" | base64 --decode > ./core/src/main/resources/application-redis.yml


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        #shell: bash
      - name: Build with Gradle
        run: ./gradlew clean :batch:build --exclude-task test
        #shell: bash
      - name: 도커 이미지 빌드 및 도커 허브 푸쉬
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t wm-batch-server ./batch
          docker tag wm-batch-server ${{ secrets.DOCKERHUB_USERNAME }}/wm-batch-server:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wm-batch-server:${GITHUB_SHA::7}
          touch ./core/src/main/resources/application-redis.yml
          echo "${{ secrets.APPLICATION_REDIS }}" | base64 --decode > ./core/src/main/resources/application-redis.yml

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_REMOTE_IP }}
          username: ${{ secrets.EC2_REMOTE_SSH_ID }}
          password: ${{ secrets.EC2_REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.EC2_REMOTE_SSH_PORT }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f wm-batch-server
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/wm-batch-server:${GITHUB_SHA::7}
            docker run -d -p 8081:8081 --name wm-batch-server --add-host host.docker.internal:host-gateway ${{ secrets.DOCKERHUB_USERNAME }}/wm-batch-server:${GITHUB_SHA::7}
            docker image prune -af

#      - name: Discord notification
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#        uses: Ilshidur/action-discord@master
#        with:
#          args: 'Deploy Batch ${{ job.status }} [${{ github.event.pull_request.title }}] - wealth marble'
#        if: always()