name: Server CD

on:
  pull_request:
    branches: [ "main", "dev", "deploy-test"]
    types:
      - closed

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/checkout@v3
      - name: 환경변수 입력
        run: |
          touch ./src/main/resources/application-mysql.yml
          echo "${{ secrets.APPLICATION }}" | base64 --decode > ./src/main/resources/application-mysql.yml
          

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        #shell: bash
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
        #shell: bash
      - name: 도커 이미지 빌드 및 도커 허브 푸쉬
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t wealth-marble-server .
          docker tag wealth-marble-server ${{ secrets.DOCKERHUB_USERNAME }}/wealth-marble-server:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wealth-marble-server:${GITHUB_SHA::7}

      - name: execute remot ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_REMOTE_IP }}
          username: ${{ secrets.EC2_REMOTE_SSH_ID }}
          password: ${{ secrets.EC2_REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.EC2_REMOTE_SSH_PORT }}
          envs: GITHUB_SHA
          script_stop: true
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/wealth-marble-server:${GITHUB_SHA::7}
            docker run -d -p 8080:8080 --name wealth-marble-server ${{ secrets.DOCKERHUB_USERNAME }}/wealth-marble-server:${GITHUB_SHA::7}
            docker image prune -f

      - name: Slack Deploy bot 실행
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Backend Deploy Success
          fields: repo,commit,message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEPLOY_URL }}
        if: always()